<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="HW1352" failures="1" tests="1" name="playwright.tests.VerifyErrorText" time="25.180" errors="0" timestamp="03 Sept 2025 13:44:39 GMT" skipped="0">
  <testcase classname="playwright.tests.VerifyErrorText" name="verifyErrorMsg" time="25.180">
    <failure message="Locator expected to contain text: Email is required
Received: Email and Password is required

Call log:
Locator.expect with timeout 5000ms
waiting for locator(&quot;.errorMessage&quot;)
  locator resolved to &lt;h2 class=&quot;errorMessage&quot;&gt;…&lt;/h2&gt;
  unexpected value &quot;Email and Password is required&quot;
  locator resolved to &lt;h2 class=&quot;errorMessage&quot;&gt;…&lt;/h2&gt;
  unexpected value &quot;Email and Password is required&quot;
  locator resolved to &lt;h2 class=&quot;errorMessage&quot;&gt;…&lt;/h2&gt;
  unexpected value &quot;Email and Password is required&quot;
  locator resolved to &lt;h2 class=&quot;errorMessage&quot;&gt;…&lt;/h2&gt;
  unexpected value &quot;Email and Password is required&quot;
  locator resolved to &lt;h2 class=&quot;errorMessage&quot;&gt;…&lt;/h2&gt;
  unexpected value &quot;Email and Password is required&quot;
  locator resolved to &lt;h2 class=&quot;errorMessage&quot;&gt;…&lt;/h2&gt;
  unexpected value &quot;Email and Password is required&quot;
  locator resolved to &lt;h2 class=&quot;errorMessage&quot;&gt;…&lt;/h2&gt;
  unexpected value &quot;Email and Password is required&quot;
  locator resolved to &lt;h2 class=&quot;errorMessage&quot;&gt;…&lt;/h2&gt;
  unexpected value &quot;Email and Password is required&quot;
  locator resolved to &lt;h2 class=&quot;errorMessage&quot;&gt;…&lt;/h2&gt;
  unexpected value &quot;Email and Password is required&quot;" type="org.opentest4j.AssertionFailedError">
      <![CDATA[org.opentest4j.AssertionFailedError: Locator expected to contain text: Email is required
Received: Email and Password is required

Call log:
Locator.expect with timeout 5000ms
waiting for locator(".errorMessage")
  locator resolved to <h2 class="errorMessage">…</h2>
  unexpected value "Email and Password is required"
  locator resolved to <h2 class="errorMessage">…</h2>
  unexpected value "Email and Password is required"
  locator resolved to <h2 class="errorMessage">…</h2>
  unexpected value "Email and Password is required"
  locator resolved to <h2 class="errorMessage">…</h2>
  unexpected value "Email and Password is required"
  locator resolved to <h2 class="errorMessage">…</h2>
  unexpected value "Email and Password is required"
  locator resolved to <h2 class="errorMessage">…</h2>
  unexpected value "Email and Password is required"
  locator resolved to <h2 class="errorMessage">…</h2>
  unexpected value "Email and Password is required"
  locator resolved to <h2 class="errorMessage">…</h2>
  unexpected value "Email and Password is required"
  locator resolved to <h2 class="errorMessage">…</h2>
  unexpected value "Email and Password is required"
at com.microsoft.playwright.impl.AssertionsBase.expectImpl(AssertionsBase.java:73)
at com.microsoft.playwright.impl.AssertionsBase.expectImpl(AssertionsBase.java:50)
at com.microsoft.playwright.impl.AssertionsBase.expectImpl(AssertionsBase.java:41)
at com.microsoft.playwright.impl.LocatorAssertionsImpl.containsText(LocatorAssertionsImpl.java:46)
at com.microsoft.playwright.assertions.LocatorAssertions.containsText(LocatorAssertions.java:724)
at playwright.tests.VerifyErrorText.verifyErrorMsg(VerifyErrorText.java:27)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- verifyErrorMsg -->
</testsuite> <!-- playwright.tests.VerifyErrorText -->
